readme.md
=> more jokes

readme.md
For more info visit: http://its-not-its.info/
P.S.: Thanks for this great repo.
=> fix: changed "it's" to "its" #grammarnazi

readme.md
Added a more few jokes at the end.
=> Add some new dad jokes.

readme.md
=> developer joke about cache

readme.md
Was reading through these and noticed one of the horizontal rules was messed up. It bugged me enough, so here you go 😂
=> Fix Horizontal Rule

readme.md
Just a couple of tweaks to make things neutral
=> Changed unnecessary gender gags

readme.md
=> Boolean Joke

readme.md
=> Write Permissions

readme.md
Thanks for the jokes, enjoyed 'em!
=> fixed grammar error to possessive `its`

readme.md
=> Add the female developer joke

readme.md
=> Bad dad jokes

readme.md
=> Add some favourite gags

readme.md
Recommit due to previous formatting error. See [PR#69](https://github.com/wesbos/dad-jokes/pull/69)
Damn, I wasted such a good unsigned int.
=> Added AND Gate joke

readme.md
Source: https://twitter.com/Mr_DrinksOnMe/status/1084078793919209479
=> A programmer was arrested for writing unreadable code

readme.md
Q: What did the process say after working in an infinite loop all day? 
A: I need a break.
=> Add a dumb joke

readme.md
Why did the document store database not get franchised? It has noSQL.
=> document store not franchised

readme.md
=> Adding terrible sql dating joke, #noRegerts

readme.md
A little more dated of a pun than when I first heard it, but I thought it was worth a pull request, anyway. Hopefully it'll at least give you a chuckle as well as a cringe 😏
=> Adds a pun, and fixes a tiny formatting error

readme.md
Layout is off.
Fixed it.
please review!
=> Fix layout

readme.md
=> Add a couple of jokes

readme.md
I know this one is a bit different.
=> Knock Knock!

readme.md
> You _checkout_ their branch 🥁🤯
This is my contribution to the cause! I came up with it this morning and knew I had to add it.
=> How do you get the code for the bank vault?

readme.md
=> Added joke

readme.md
Compliments of @kenwheeler https://twitter.com/ken_wheeler/status/1101263005185118209
=> Foo bar joke

readme.md
Trying to include "await" as wait :flushed:
=> Asynchronous JavaScript is amazing joke v2

readme.md
Adding the pirate joke from https://github.com/wesbos/dad-jokes/pull/30
=> Link - Pirates love programming

readme.md
Also added a missing question mark to my Parroty Error joke :)
=> A couple of HTTP code jokes

readme.md
Cleanup repeated joke.
I'm way too emotionally invested in this repo 😂
=> Delete repeated asynchronous JS pun

readme.md
My life is spiraling out of control.
=> #LOL #TERRIFIC

readme.md
Aptly I also recently became a father 🥰
=> Added crypto gag

readme.md
I corrected a typo and added:
**Q**: Why are keyboards always working so hard?
**A**: Cause they have two shifts!
=> I corrected a typo and added one joke.

readme.md
Hat tip to my wife for this one.  Her dad joke game is far better than mine.
=> Adding a joke

readme.md
Heard this years ago on the Security Now podcast.
=> This joke makes me hungry

readme.md
I submitted and merged my first joke on Valentines Day 2019: https://github.com/wesbos/dad-jokes/pull/95
Thought I'd come back for Round 2. Thank you @wesbos for this amazing repo!
=> Buzzy Jokes Are All The Rage

readme.md
=> New dad jokes

readme.md
Added the Corduroy pillow joke.  I hope that it's funny!
=> Adding a joke to the end of the file

readme.md
**Q:** Why is it called the Dark Ages?
**A:** There were a lot of KNIGHTS!
=> ♘ Jokes about knights

readme.md
Looks like there might have been a merge conflict at one point.
=> Fix formatting

readme.md
Since it's coming up to Halloween, have a witch joke :)
=> Witch joke

readme.md
https://twitter.com/joshmanders/status/1322595351728148480
=> top tier dad joke

readme.md
Hopefully funny, not scary
God Bless
=> Adding new joke

readme.md
=> Add ALU joke

readme.md
=> baby developer

readme.md
https://www.reddit.com/r/ProgrammerHumor/comments/v4nc3b/business_is_booming/
=> Very profitable

readme.md
=> Add python joke

readme.md
=> Fix typo - remove quote

readme.md
=>  Sea Sharp Boat

readme.md
=> What is a package manager's favorite holiday?

readme.md
=> Why do astronauts use Linux?

readme.md
Sorry, the prettier on my IDE removes whitespace (that edit wasn't intentional).
=> Why did the stoner attend the cryptography conference?

readme.md
Explanation: Golang, `git fetch`, and html tag for link `<a>`.
DISCLOSURE I am not a dad.
=> Miscellanous Puns
